# Generated by Django 4.0.4 on 2022-06-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(default='default', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
